spring:
  application:
    name: nosql_lab1
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/nosql_lab1}
    username: ${POSTGRES_USER:nosql_lab1}
    password: ${POSTGRES_PASSWORD:nosql_lab1}
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      format-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE:0}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.internal-auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL}
  internal-auth-server-url: ${KEYCLOAK_INTERNAL_URL}
  realm: ${KEYCLOAK_REALM}
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
